### ISSUE TITLE
"waiting for LeagueClient to connect"

### ISSUE THREAD

**Issue by JokerOfRage** [LarsBaertschi/lol-champselect-ui#113]
Well, the Backend won't connect to the LeagueClient, I tried admin / no admin, I tried reinstalling, doing the --force. No help.
This is for EUNE region. I don't know if it is on any other regions as well. I tried firewall off, Admin access to everything. Still doesn't work! Any help is appreciated! Cheer
![Screenshot_1](https://user-images.githubusercontent.com/74517142/137008177-fabc57cb-3970-49bf-85b4-2996c940d554.png)
s.

**Comment by JokerOfRage** [comment]
Okay, I did all of these and here are the results.

Prior to this I reinstalled the whole backend and layouts, but while installing backend this was a warning I got:

![Screenshot_1](https://user-images.githubusercontent.com/74517142/137186438-4cc06b6c-8860-4613-bbde-0c80071ae106.png)

`npm start -- --debug --leaguepath:
`
![Screenshot_2](https://user-images.githubusercontent.com/74517142/137186491-ed18e3cb-5162-4098-8f4f-7527089f171a.png)

Not connected to LCU and can't connect to leagueClient

`npm start -- --debug --experimentalConnector
`
![Screenshot_3](https://user-images.githubusercontent.com/74517142/137186590-ba8f4e13-fb5e-4a0c-91ea-4529da53f169.png)

Can't connect to LCU, but also can't conncet / locate leagueClient, also it failed to locate it and asks is it running.

`npm start -- --debug --experimentalConnector --leaguePath
`
![Screenshot_5](https://user-images.githubusercontent.com/74517142/137186829-e60d369a-a683-4bc5-a8df-87d1aa352fa1.png)

Pretty much the same error as in the one prior to this one.

League Client was OPEN during testing, not ran by admin. Windows firewall off as well. Also I am not sure if the LCU was already resolved in one of these issues but this error sounded familiar to me.
Love the project btw, hope this helps you.
Cheers.

**Comment by LarsBaertschi** [comment]
Hey, thank you for providing said information!

About point two, I was actually wrong, please excuse. Instead, try opening "Command Prompt" (you can find it in Windows by searching for CMD) and there execute the same command: `WMIC PROCESS WHERE name='LeagueClientUx.exe' GET commandline` while the league client is open.
